{% set name = "chartify" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bb00d2e2fca0fcb6a211c04e4419ee289a484dc88c2d4bfb006071a3280a9c37


build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - bokeh >=2.0.0,<3.0.0
    - colour >=0.1.5
    - jupyter >=1.0.0,<2.0.0
    - pandas >=1.0.0,<2.0.0
    - pillow >=6.2.0
    - python >=3.5
    - scipy >=1.0.0,<2.0.0
    - selenium >=3.7.0,<=3.8.0

test:
  imports:
    - chartify

about:
  home: https://github.com/spotify/chartify
  license: Apache 2.0
  license_file: LICENSE
  summary: Python library to make plotting simpler for data scientists

extra:
  recipe-maintainers:
    - cphalpert
    - apcamargo
