{% set name = "chartify" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6f621a5f342fa8f143e0cedb74e4537cfaeec796331744718b4d0744ba127965


build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - bokeh >=3.4.2
    - colour >=0.1.5
    - ipykernel >=6.0
    - ipython >=7.17.0
    - pandas >=1.2.0
    - pillow >=9.1.0
    - python >={{ python_min }}
    - scipy >=1.6.0
    - selenium >=4.0.0
    - pyyaml >=6.0.0
    - jinja2 >=3.1.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - chartify

about:
  home: https://github.com/spotify/chartify
  license: Apache-2.0
  license_file: LICENSE
  summary: Python library to make plotting simpler for data scientists

extra:
  recipe-maintainers:
    - cphalpert
    - apcamargo
