travis:
  secure:
    BINSTAR_TOKEN: 47KnyXDSdD7I6Vh+qvWULhAuuu0xsUL78WRy1LyjTe7+SdODmv2dpDAvRCmGFy+rqIlMog86tG0JCkG+eLIN4tJ9gUMS7ZIwv7ncXng1/bu+9NeRWURCEG+cGfza22/JU9L3KiTKu6Nq9DlxE4VEIum+XbNO5j7RErzxpdEAgeTIYPuLnZXjaXNaI5GmdPrTmG4rPMC/cuZSxAHsstE13aIGS4JQuX9D1SCyLRz3J6W82ZBABXaX1udbMR8N9KwhzHTLG/Ch1yLlbjw8Qv4vOc9hLk6oy6yr6/uGvq7Osa4+cJnwMS6PvH9jMlt+bop6zbsULjtqpMYHTVa9kn4KpF7oOzFJMIkZf507zH8rzEnHgfhbTXlwKWbjwjEJFsSIPslCRHl/3mjLplsrdcBcNpO01AdusXO8ud1hh+8XVezxcyLcSCU9fmA+XkkRRj+W2+4B9A8Q7Z7AS0jw9mcKrfa6N2OjFlKX12h5FSnIbRLVFvRs+7F3RXgrTxhVlXBd/uKXt9fR8Gic0b1/kiQpELq+eDPpOKftZq5r0L1j3U8pFH1jLIf7JUQ4dE0zcx66jhighcUXMKLY5E06cdC9W1W58SP3wXmtLmYd8O02ZwSRiSKptxN9hoAKc5UYYf/lUSopV2Vksc9F2hzqEp43j12c86mFp0FdBOYdtcbl90U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
